--H2 DB
create table board
(
    id bigint generated by default as identity,
    content TEXT not null,
    hit bigint not null,
    created_at timestamp not null,
    title varchar(255) not null,
    writer varchar(20) not null,
    primary key (id)
)